"""Menu progression per city.

Each stage unlocks new dishes automatically, and also offers "locked" dishes the
player buys with coins. Stage 3+ adds a special (spesial) dish, stage 5 a
legendary one; specials and legendaries are always coin-locked. Combos give a bonus when both items are on the menu.

Fields per item:
  id, name, kind (makanan|minuman|dessert), stage, unlock ("stage" | "coins"),
  tier ("biasa" | "spesial" | "legendaris"), icon (template + colours, see food.py)

Numbers (price, cook time, unlock cost) are generated by `economy()` so the
curve can be tuned in one place.
"""

M, D, S = "makanan", "minuman", "dessert"


def item(id_, name, kind, stage, icon, unlock="stage", tier="biasa"):
    if tier != "biasa":                     # menu spesial & legendaris selalu dibuka pakai koin
        unlock = "coins"
    return {"id": id_, "name": name, "kind": kind, "stage": stage, "unlock": unlock,
            "tier": tier, "icon": icon}


MENU = {
    "jakarta": [
        item("kerak_telor", "Kerak Telor", M, 1, ("pancake", "#e8b04a", "#c9432a", "#f3e9d8")),
        item("es_teh_manis", "Es Teh Manis", D, 1, ("glass", "#b0662a", "#d98a3a", None)),
        item("bir_pletok", "Bir Pletok", D, 1, ("glass", "#9a2a1e", "#c9432a", "#e0b04a"), "coins"),
        item("ketoprak", "Ketoprak", M, 2, ("rice", "#f3e9d8", "#8a5a36", "#6fa044")),
        item("gado_gado", "Gado-gado", M, 2, ("salad", "#6fa044", "#c98a3a", "#f3e9d8"), "coins"),
        item("soto_betawi", "Soto Betawi", M, 3, ("bowl", "#f0d8a0", "#8a5a36", "#6fa044")),
        item("nasi_uduk", "Nasi Uduk", M, 3, ("rice", "#fbf6ec", "#c98a3a", "#e0662a")),
        item("nasi_uduk_komplit", "Nasi Uduk Komplit", M, 3,
             ("rice", "#fbf6ec", "#d98a3a", "#c9432a"), tier="spesial"),
        item("es_selendang_mayang", "Es Selendang Mayang", D, 3,
             ("glass", "#ff8fdc", "#6fa044", "#fbf6ec"), "coins"),
        item("asinan_betawi", "Asinan Betawi", M, 4, ("salad", "#c9432a", "#6fa044", "#f2c94c")),
        item("gabus_pucung", "Gabus Pucung", M, 4, ("bowl", "#2b2530", "#a8a090", "#6fa044")),
        item("es_kopi_susu", "Es Kopi Susu", D, 4, ("glass", "#e8d8b0", "#6b4a32", None)),
        item("soto_betawi_iga", "Soto Betawi Iga", M, 4,
             ("bowl", "#f0d8a0", "#74432a", "#c9432a"), tier="spesial"),
        item("kue_rangi", "Kue Rangi", S, 4, ("smallcakes", "#f3e0b0", "#8a5a36", "#fbf6ec"), "coins"),
        item("laksa_betawi", "Laksa Betawi", M, 5, ("bowl", "#f2c94c", "#c9432a", "#6fa044")),
        item("sayur_babanci", "Sayur Babanci", M, 5, ("bowl", "#e8c070", "#8a5a36", "#f3e9d8")),
        item("kerak_telor_legenda", "Kerak Telor Api Legenda", M, 5,
             ("pancake", "#f2c94c", "#ff8fdc", "#fff2a8"), tier="legendaris"),
        item("dodol_betawi_emas", "Dodol Betawi Emas", S, 5,
             ("cake", "#6b3a22", "#f2c94c", "#8a5a36"), "coins", tier="legendaris"),
    ],
    "bandung": [
        item("batagor", "Batagor", M, 1, ("pieces", "#d8a860", "#8a4a2a", "#f3e9d8")),
        item("es_cendol", "Es Cendol", D, 1, ("glass", "#f3e9d8", "#6fa044", "#6b3a22")),
        item("bajigur", "Bajigur", D, 1, ("mug", "#c9a070", "#8a5a36", None), "coins"),
        item("cireng", "Cireng", M, 2, ("pieces", "#f0e6d0", "#c9432a", "#d8c8a0")),
        item("cilok", "Cilok", M, 2, ("skewer", "#e8e0d0", "#8a4a2a", "#c9432a"), "coins"),
        item("seblak", "Seblak", M, 3, ("bowl", "#d8432a", "#f3e0b0", "#6fa044")),
        item("mie_kocok", "Mie Kocok", M, 3, ("bowl", "#e8c878", "#f2c94c", "#6fa044")),
        item("seblak_komplit", "Seblak Komplit", M, 3,
             ("bowl", "#c9322a", "#f3e0b0", "#f2a93b"), tier="spesial"),
        item("bandrek", "Bandrek", D, 3, ("mug", "#8a5a36", "#c98a3a", None), "coins"),
        item("surabi", "Surabi", M, 4, ("pancake", "#f0e0c0", "#6b3a22", "#f2c94c")),
        item("nasi_timbel", "Nasi Timbel", M, 4, ("leafrice", "#fbf6ec", "#6fa044", "#c98a3a")),
        item("es_goyobod", "Es Goyobod", D, 4, ("glass", "#f3e9d8", "#8a5a36", "#6fa044")),
        item("timbel_komplit", "Nasi Timbel Komplit", M, 4,
             ("leafrice", "#fbf6ec", "#c9432a", "#f2c94c"), tier="spesial"),
        item("colenak", "Colenak", S, 4, ("skewer", "#f3e0b0", "#6b3a22", "#c9a070"), "coins"),
        item("karedok", "Karedok", M, 5, ("salad", "#8ab050", "#c98a3a", "#f3e9d8")),
        item("mie_kocok_kikil", "Mie Kocok Kikil", M, 5, ("bowl", "#e8c878", "#d8c8a0", "#c9432a")),
        item("batagor_kristal", "Batagor Kristal Tangkuban", M, 5,
             ("pieces", "#a8e0f0", "#ff8fdc", "#fff2a8"), tier="legendaris"),
        item("surabi_bulan_emas", "Surabi Bulan Emas", S, 5,
             ("pancake", "#f2c94c", "#fff2a8", "#ff8fdc"), "coins", tier="legendaris"),
    ],
    "bali": [
        item("sate_lilit", "Sate Lilit", M, 1, ("sate", "#e0b070", "#c9432a", "#e2c678")),
        item("es_kelapa_muda", "Es Kelapa Muda", D, 1, ("coconut", "#6fa044", "#f3f0ea", None)),
        item("loloh_cemcem", "Loloh Cemcem", D, 1, ("glass", "#8ab050", "#f2c94c", None), "coins"),
        item("tipat_cantok", "Tipat Cantok", M, 2, ("salad", "#e8e0c0", "#a8602a", "#6fa044")),
        item("nasi_jinggo", "Nasi Jinggo", M, 2, ("leafrice", "#fbf6ec", "#c9432a", "#a8602a"), "coins"),
        item("ayam_betutu", "Ayam Betutu", M, 3, ("chicken", "#c98a3a", "#f2c94c", "#6fa044")),
        item("lawar", "Lawar", M, 3, ("salad", "#8ab050", "#c9432a", "#f3e9d8")),
        item("nasi_campur_bali", "Nasi Campur Bali", M, 3,
             ("rice", "#fbf6ec", "#c9432a", "#6fa044"), tier="spesial"),
        item("es_daluman", "Es Daluman", D, 3, ("glass", "#4f8a3a", "#f3e9d8", "#6b3a22"), "coins"),
        item("bebek_betutu", "Bebek Betutu", M, 4, ("chicken", "#a8602a", "#f2c94c", "#6fa044")),
        item("serombotan", "Serombotan", M, 4, ("salad", "#6fa044", "#d98a3a", "#c9432a")),
        item("es_kopi_kintamani", "Es Kopi Kintamani", D, 4, ("glass", "#4a2a1e", "#e8d8b0", None)),
        item("betutu_utuh", "Ayam Betutu Utuh", M, 4,
             ("chicken", "#b8702a", "#f2c94c", "#c9432a"), tier="spesial"),
        item("jaje_laklak", "Jaje Laklak", S, 4, ("smallcakes", "#6fb070", "#fbf6ec", "#6b3a22"), "coins"),
        item("sate_plecing", "Sate Plecing", M, 5, ("sate", "#c98a3a", "#d8322a", "#6fa044")),
        item("tum_ayam", "Tum Ayam", M, 5, ("leafrice", "#e8c070", "#6fa044", "#c9432a")),
        item("betutu_api_dewata", "Betutu Api Dewata", M, 5,
             ("chicken", "#f2c94c", "#ff8fdc", "#fff2a8"), tier="legendaris"),
        item("bubuh_injin_pelangi", "Bubuh Injin Pelangi", S, 5,
             ("bowl", "#4a2a4a", "#fbf6ec", "#ff8fdc"), "coins", tier="legendaris"),
    ],
    "surabaya": [
        item("rawon", "Rawon", M, 1, ("bowl", "#2b2020", "#8a5a36", "#6fa044")),
        item("es_degan", "Es Degan", D, 1, ("coconut", "#8ab050", "#f3f0ea", None)),
        item("es_dawet", "Es Dawet", D, 1, ("glass", "#f3e9d8", "#6fa044", "#6b3a22"), "coins"),
        item("tahu_tek", "Tahu Tek", M, 2, ("pieces", "#f0d8a0", "#8a4a2a", "#6fa044")),
        item("tahu_campur", "Tahu Campur", M, 2, ("bowl", "#c98a3a", "#f0d8a0", "#6fa044"), "coins"),
        item("lontong_balap", "Lontong Balap", M, 3, ("bowl", "#e8c878", "#f0e0b0", "#6fa044")),
        item("rujak_cingur", "Rujak Cingur", M, 3, ("salad", "#5a3a2a", "#6fa044", "#f3e9d8")),
        item("rawon_setan", "Rawon Setan", M, 3,
             ("bowl", "#1e1616", "#c9432a", "#f2c94c"), tier="spesial"),
        item("es_sinom", "Es Sinom", D, 3, ("glass", "#f2b83a", "#6fa044", None), "coins"),
        item("sate_klopo", "Sate Klopo", M, 4, ("sate", "#b8702a", "#f3e9d8", "#6b3a22")),
        item("lontong_kupang", "Lontong Kupang", M, 4, ("bowl", "#d8c8a0", "#8a5a36", "#6fa044")),
        item("es_kopi_tubruk", "Es Kopi Tubruk", D, 4, ("glass", "#3a2a22", "#6b4a32", None)),
        item("rawon_iga", "Rawon Iga Komplit", M, 4,
             ("bowl", "#2b2020", "#74432a", "#f2c94c"), tier="spesial"),
        item("lapis_surabaya", "Lapis Surabaya", S, 4, ("cake", "#f2c94c", "#6b3a22", "#f0d8a0"), "coins"),
        item("nasi_cumi_hitam", "Nasi Cumi Hitam", M, 5, ("rice", "#fbf6ec", "#2b2530", "#c9432a")),
        item("pecel_semanggi", "Pecel Semanggi", M, 5, ("leafrice", "#4f8a3a", "#a8602a", "#f3e9d8")),
        item("rawon_api_legenda", "Rawon Api Legenda", M, 5,
             ("bowl", "#2a1030", "#ff8fdc", "#f2c94c"), tier="legendaris"),
        item("rujak_cingur_mahkota", "Rujak Cingur Mahkota", M, 5,
             ("salad", "#5a3a2a", "#f2c94c", "#ff8fdc"), "coins", tier="legendaris"),
    ],
}

# Combos: bonus when every item is on the active menu at once.
COMBOS = {
    "jakarta": [("Paket Ngopi Betawi", ["kerak_telor", "bir_pletok"], 1.15),
                ("Sarapan Jakarte", ["nasi_uduk", "es_teh_manis"], 1.2),
                ("Soto Seger", ["soto_betawi", "es_selendang_mayang"], 1.25),
                ("Pesta Palang Pintu", ["soto_betawi_iga", "asinan_betawi", "kue_rangi"], 1.4)],
    "bandung": [("Jajan Pasar Baru", ["batagor", "es_cendol"], 1.15),
                ("Anget Lembang", ["surabi", "bajigur"], 1.2),
                ("Pedes Nampol", ["seblak", "es_goyobod"], 1.25),
                ("Botram Sunda", ["timbel_komplit", "karedok", "colenak"], 1.4)],
    "bali": [("Sore di Pantai", ["sate_lilit", "es_kelapa_muda"], 1.15),
             ("Megibung", ["ayam_betutu", "lawar", "loloh_cemcem"], 1.3),
             ("Manis Sanur", ["jaje_laklak", "es_kopi_kintamani"], 1.2),
             ("Upacara Agung", ["betutu_utuh", "serombotan", "es_daluman"], 1.4)],
    "surabaya": [("Arek Suroboyo", ["rawon", "es_degan"], 1.15),
                 ("Cangkruk Malam", ["tahu_tek", "es_dawet"], 1.2),
                 ("Pedes Setan", ["rawon_setan", "es_sinom"], 1.3),
                 ("Jamuan Tunjungan", ["rawon_iga", "sate_klopo", "lapis_surabaya"], 1.4)],
}

TIER_MULT = {"biasa": 1.0, "spesial": 2.5, "legendaris": 8.0}
KIND_MULT = {"makanan": 1.0, "minuman": 0.6, "dessert": 1.3}


def economy(it, city_index):
    """Starting balance numbers (tune freely). Each stage ~x4, each city ~x10."""
    base = 10 * (4 ** (it["stage"] - 1)) * (10 ** city_index)
    price = round(base * TIER_MULT[it["tier"]] * KIND_MULT[it["kind"]])
    return {
        "price": price,
        "cook_seconds": round(2 + it["stage"] * 1.5 + (3 if it["tier"] != "biasa" else 0), 1),
        "unlock_cost": price * 60 if it["unlock"] == "coins" else 0,
    }
